[package]
name = "wayvek"
version = "0.1.0"
edition = "2024"

[dependencies]
wayland-client = { version = "0.31.15", features = ["dlopen"] }
wayland-protocols = { version = "0.32.13", features = ["client", "unstable"] }
ash = "0.38.0"
drm-fourcc = "2.2.0"
rustix = { version = "1", features = ["fs", "mm"] }
zerocopy = { version = "0.8", features = ["derive"] }
